version: "3.8"

#创建网桥
networks:
    net1:
        name: my_net
        driver: bridge #指定网络模式
        ipam:
            driver: default
            config:
                - subnet: 172.1.1.0/24 #指定ip段

#创建卷
volumes:
    my_volume:
        name: my_volume_name #在宿主机的目录名

# 定义日志模板
x-logging: &default-logging
    driver: json-file
    options:
        max-size: "200k"
        max-file: "10"

services:
    nginx:
        image: nginx:1.19-alpine
        container_name: nginx
        hostname: docker-nginx
        depends_on: #启动顺序
          - mysql
          - mongodb
          - redis
          - memcached
          - rabbitmq
          - php
        command: /bin/sh -c "adduser -D -H -h /var/cache/nginx -s /sbin/nologin -G www-data www-data && nginx -g 'daemon off;'"
        working_dir: /var/www/web/ #进入容器的默认目录
        environment:
            - TZ=Asia/Shanghai
        restart: always
        ports:
          - 80:80
          - 443:443
        volumes:
            - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${PWD}/nginx/server.fastcgi.conf:/etc/nginx/server.fastcgi.conf:ro
            - ${PWD}/nginx/cert/api.crt:/etc/nginx/api.crt:ro
            - ${PWD}/nginx/cert/api.key:/etc/nginx/api.key:ro
            - ${PWD}/nginx/cert/ssl.crt:/etc/nginx/ssl.crt:ro
            - ${PWD}/nginx/cert/ssl.key:/etc/nginx/ssl.key:ro
            - ${PWD}/nginx/cert/eelly.com.crt:/etc/nginx/eelly.com.crt:ro
            - ${PWD}/nginx/cert/eelly.com.key:/etc/nginx/eelly.com.key:ro
            - ${PWD}/nginx/vhost/:/etc/nginx/vhost/:ro
            - ${PWD}/nginx/rewrite/:/etc/nginx/rewrite/:ro
            - ${PWD}/../../eelly/:/var/www/web/:rw #项目
            - ${PWD}/data/logs/nginx/:/var/log/nginx/:rw
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.99
                aliases:
                    - api.eelly.develop
                    - m.eelly.develop
                    - oauth.eelly.develop
                    - account.eelly.develop
                    - www.eelly.develop
                    - video.eelly.develop
                    - manage.eelly.develop
                    - www.127mc.develop

    php:
        # build: ./php7-fpm
        image: ghcr.io/twbworld/php-eelly:latest
        container_name: php
        hostname: docker-php
        depends_on: #启动顺序
          - mysql
          - mongodb
          - redis
          - memcached
          - rabbitmq
        environment:
            - TZ=Asia/Shanghai
        restart: always
        ports:
            - 9000:9000
            - 9501:9501
        working_dir: /var/www/web/ #进入容器的默认目录
        volumes:
            - ${PWD}/php7-fpm/php.ini:/usr/local/etc/php/php.ini:ro
            - ${PWD}/php7-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ${PWD}/../../eelly/:/var/www/web/:rw #项目
            - ${PWD}/data/logs/php/:/var/log/php/:rw
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro #composer下载项目需要gitee的验证
            - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.98

    redis:
        image: redis:6.0
        container_name: redis
        hostname: docker-redis
        restart: always
        ports:
            - 6379:6379
        environment:
            - TZ=Asia/Shanghai
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.97

    mysql:
        image: mysql:5.7
        container_name: mysql
        hostname: docker-mysql
        command: /bin/bash -c "chown -R www-data:www-data /var/lib/mysql /var/run/mysqld &&  mysqld"
        environment: #设置环境变量
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=devmall
            - MYSQL_USER=devmall
            - MYSQL_PASSWORD=devmall
            # - MYSQL_DATABASE=tp
        restart: always
        ports:
            - 3306:3306
        volumes:
          # - ${PWD}/data/eelly.sql:/docker-entrypoint-initdb.d/eelly.sql:ro #把sql放在docker-entrypoint-initdb.d下,mysql会自动执行
          - ${PWD}/data/mysql-data/:/var/lib/mysql/:rw #库数据,一旦使用,设置的环境变量和自动执行sql功能则失效
          - ${PWD}/data/logs/mysql/:/var/www/logs/:rw
          - ${PWD}/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro #配置文件
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.96

    memcached:
        image: memcached:latest
        container_name: memcached
        hostname: docker-memcached
        ports:
            - 11211:11211
        environment:
            - TZ=Asia/Shanghai
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.95

    mongodb:
        image: mongo:4.2-bionic
        container_name: mongo
        hostname: docker-mongo
        ports:
            - 27017:27017
        environment:
            - TZ=Asia/Shanghai
            - ME_CONFIG_MONGODB_ADMINUSERNAME=abc
            - ME_CONFIG_MONGODB_ADMINPASSWORD=abc123456
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.94

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: docker-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - TZ=Asia/Shanghai
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.93
