version: "3.8"

#创建网桥
networks:
    net1:
        name: my_net
        driver: bridge #指定网络模式
        ipam:
            driver: default
            config:
                - subnet: 172.1.1.0/24 #指定ip段

#创建卷
volumes:
    my_volume:
        name: my_volume_name #在宿主机的目录名

# 定义日志模板
x-logging: &default-logging
    driver: json-file
    options:
        max-size: "200k"
        max-file: "10"

services:
    web:
        image: nginx:1.19
        container_name: nginx_container_name
        hostname: nginx_hostname
        ports:
            - 80:80
            - 443:443
        working_dir: /usr/share/nginx #进入容器的默认目录
        volumes:
            - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf:ro #nginx根配置
            - ${PWD}/conf/default.conf:/etc/nginx/conf.d/default.conf:ro #nginx配置
            - ${PWD}/conf/tp.top.conf:/etc/nginx/conf.d/tp.top.conf:ro #nginx配置
            - ${PWD}/conf/twbhub.top.conf:/etc/nginx/conf.d/twbhub.top.conf:ro #nginx配置
            - ${PWD}/conf/twbhub.cf.conf:/etc/nginx/conf.d/twbhub.cf.conf:ro #nginx配置
            - ${PWD}/../admin:/usr/share/nginx/tp:rw #运行目录
            - ${PWD}/../oneindex:/usr/share/nginx/oneindex:rw #运行目录
            - my_volume:/usr/share/nginx/logs:rw #日志
        environment:
            - TZ=Asia/Shanghai
        restart: always
        logging: *default-logging
        depends_on: #启动顺序
            - sql
            - nosql
            - language
            - blog
        networks:
            net1:
                ipv4_address: 172.1.1.99

    language:
        build:
            context: ${PWD}/conf/php-phalcon-swoole-redis
            dockerfile: Dockerfile
        image: twbworld/php-phalcon-swoole-redis:latest
        container_name: php_container_name
        hostname: php_hostname
        ports:
            - 9000:9000
            - 9501:9501
        working_dir: /usr/share/nginx #进入容器的默认目录
        volumes:
            - ${PWD}/../admin:/usr/share/nginx/tp:rw
            - ${PWD}/../oneindex:/usr/share/nginx/oneindex:rw
        environment:
            - TZ=Asia/Shanghai
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.98

    sql:
        image: mysql:8.0
        container_name: mysql_container_name
        hostname: mysql_hostname
        ports:
            - 3306:3306
        volumes:
            - ${PWD}/../admin/docs/tp.sql:/docker-entrypoint-initdb.d/tp.sql:ro #把sql放在docker-entrypoint-initdb.d下,mysql会自动执行
            - /usr/local/mysql8-docker/data/:/var/lib/mysql:rw #库数据
            - ${PWD}/conf/mysql8.cnf:/etc/mysql/conf.d/mysql8.cnf:ro #配置文件
        environment: #设置环境变量
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=tp
            - MYSQL_USER=tp
            - MYSQL_PASSWORD=tp
            - MYSQL_DATABASE=tp
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.97

    nosql:
        image: redis:6.0
        container_name: redis_container_name
        hostname: redis_hostname
        ports:
            - 6379:6379
        environment:
            - TZ=Asia/Shanghai
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.96

    blog:
        build:
            context: ${PWD}/conf/hugo-go-git
            dockerfile: Dockerfile
        image: twbworld/hugo-go-git:latest
        container_name: blog_container_name
        hostname: blog_hostname
        working_dir: /src
        command: server
        ports:
            - 1313:1313
        volumes:
            - ${PWD}/../blog:/src:rw #hugo项目的根目录
        environment:
            - TZ=Asia/Shanghai
            - HUGO_BIND=0.0.0.0
            - HUGO_ENV=DEV # DEV || production
        restart: always
        logging: *default-logging
        networks:
            net1:
                ipv4_address: 172.1.1.95
