name: cd
on:
  workflow_dispatch: #github页面手动触发
  push: #push即触发
    branches:
      - master
    paths-ignore: #不作为触发的文件
      - '.*'
      - 'LICENSE'
      - 'README.md'
jobs:
  cd:
    runs-on: ubuntu-20.04 #虚拟环境(github提供)
    env:
      TZ: Asia/Shanghai
    steps:
      - name: pull-repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/docker/
            git checkout -- .
            git checkout master
            git fetch origin master
            git merge origin/master
      - name: restart-nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker restart nginx && exit
