name: ci
on:
  workflow_dispatch: #github页面手动触发
  push: #push即触发
    branches:
      - main
    paths-ignore: #不作为触发的文件
      - '.*'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.*'
      - 'LICENSE'
      - 'README.md'
jobs:
  ci:
    runs-on: ubuntu-20.04 #虚拟环境(github提供)
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      # 运行Codacy,可使用.codacy.yml配置
      - name: Codacy
        uses: codacy/codacy-analysis-cli-action@master
        with:
          # tool: PHP_CodeSniffer,PHP Mess Detector,PHPCPD,PHP Depend,phpmd,phpcs #参考: https://docs.codacy.com/getting-started/supported-languages-and-tools/
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true #上传"代码质量"报告到Codacy(因为本地审查代码,要关闭远程Codacy的审查功能(Repository analysis开启))
          format: sarif
          output: ../results.sarif #要求干净的环境,把文件放在项目外,否则会报错
          gh-code-scanning-compat: true #兼容Github的报错等级
          verbose: true #列出详情
          max-allowed-issues: 2147483647 #允许最大的"问题数"
      # 对接Github的Security菜单
      - name: Upload-github-sarif-reporter
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results.sarif

  cd:
    needs: ci
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: pull-repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/docker/
            git checkout -- .
            git clean -df
            git checkout main
            git fetch origin main
            git reset --hard origin/main
            exit
      - name: restart-nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker exec nginx /bin/bash -c 'nginx -t && service nginx force-reload && exit'
            exit
